-- V16: insights — AI-generated daily insights for Standard subscribers.
-- Generated by DailyScoreJob via Claude API (web_search tool) at 06:00 EAT.
-- Each Standard user gets up to 3 insights per day; dedup guard prevents re-generation.

CREATE TABLE insights (
    id               BIGSERIAL PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title            TEXT   NOT NULL,
    body             TEXT   NOT NULL,
    action_text      TEXT,
    module_code      VARCHAR(20),
    is_read          BOOLEAN     NOT NULL DEFAULT FALSE,
    generated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_insights_user ON insights(user_id, generated_at DESC);
