-- V8: user_alerts — per-user risk alerts generated by the daily scoring run.
-- severity mirrors Band but only URGENT/ACT_NOW/WATCH_OUT (ALL_GOOD never triggers an alert).
-- month_key ('YYYY-MM') pairs with users.monthly_alert_count to enforce the Basic 3-cap.

CREATE TABLE user_alerts (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    severity    VARCHAR(20)  NOT NULL
                  CHECK (severity IN ('URGENT', 'ACT_NOW', 'WATCH_OUT')),
    module_code VARCHAR(20)  REFERENCES risk_modules (code),
    title       VARCHAR(255) NOT NULL,
    body        TEXT         NOT NULL,
    month_key   VARCHAR(7)   NOT NULL,   -- 'YYYY-MM', e.g. '2026-06'
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_user_alerts_user_created ON user_alerts (user_id, created_at DESC);
CREATE INDEX ix_user_alerts_user_month   ON user_alerts (user_id, month_key);
